### ISSUE TITLE
Problems on Mac Quick Start

### ISSUE THREAD

**Issue by nikoagge** [spark3dp/print-manager#28]
I have npm 2.3.0 but when I try npm install it gives me this error: 

npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.11.16
npm ERR! npm  v2.3.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'async-some'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/NikolaosAngelidis/Desktop/Programming/Spark/print-manager-1.5/spark-print-mgr/npm-debug.log

and when i try node server.js it gives me this error: 

/Users/NikolaosAngelidis/Desktop/Programming/Spark/print-manager-1.5/spark-print-mgr/config.js:178
{ "roopaServerPath" : "/Users/NikolaosAngelidis/Desktop/Programming/Spark/Roop
                    ^
SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/NikolaosAngelidis/Desktop/Programming/Spark/print-manager-1.5/spark-print-mgr/app.js:2:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Any ideas?

**Comment by ghost** [comment]
I do not know what you have problems with this.

You can try deleting node_modules and starting again.

sudo rm -f node_modules
sudo npm install

If this fails try a simple test to see if your environment is set up to do node/c++ dev work 

"npm install serialport@1.6.1" if this does not succeed then you should investigate those issues.

**Comment by nikoagge** [comment]
Ok, I ‘ve changed some things but this time it gives me this:

info: All database printers have been initialized
info: initialized device monitor
error: cannot find mdns
error: cannot find or initialize usb or usb-detection module
warn: cannot find serialport or usb-detection modules
info: started SerialDiscovery
info: started EmberDiscovery
info: starting conveyor discovery
error: uncaughtException: bind EADDRINUSE date=Thu May 05 2016 19:01:36 GMT+0300 (EEST), pid=7298, uid=501, gid=20, cwd=/Users/NikolaosAngelidis/Desktop/Programming/Spark/print-manager-1.5/spark-print-mgr, execPath=/usr/local/bin/node, version=v0.11.16, argv=[node, /Users/NikolaosAngelidis/Desktop/Programming/Spark/print-manager-1.5/spark-print-mgr/server.js], rss=73580544, heapTotal=58682624, heapUsed=30854984, loadavg=[1.65478515625, 1.71875, 1.71923828125], uptime=37559, trace=[column=11, file=util.js, function=exports._errnoException, line=746, method=_errnoException, native=false, column=28, file=dgram.js, function=null, line=224, method=null, native=false, column=18, file=dns.js, function=null, line=85, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[Error: bind EADDRINUSE,     at exports._errnoException (util.js:746:11),     at dgram.js:224:28,     at dns.js:85:18,     at process._tickCallback (node.js:355:11)]
info: saving data before exit

Any idea?

Nikos

**Comment by nikoagge** [comment]
Actually to start and do some things i changed the port here http://localhost:61000/console/#/settings. If i let initial port(9998) as you say on the documentation it gives me nothing but errors. The one i ‘ve sent you before.

Nikos

**Comment by ghost** [comment]
You have printStudio installed which automatically starts its version of PrintManger as a daemon. So you would need to turn that off. Thats documented in PrintStudio docs.

"sudo launchctl unload /Library/LaunchDaemons/com.autodesk.printmanager.plist"

You also found the alternative way of changing the port.

This still not work, you are not building mdns, serial port or usb-detection which means that you are not set up to do node/c++ development.

try this

npm install serialport@1.6.1 

Take a look at the requirements of building serialport by checking out https://www.npmjs.com/package/serialport once you can build this the rest of print manager will work.

**Comment by nikoagge** [comment]
Ok, I would like to do this but I didn't know how. Thanks for the advice, I 'm gonna try and I 'll let you know about the result.

Nikos

**Comment by nikoagge** [comment]
It still gives me the same error and I ‘ve really tried everything. Maybe should I use a newer version of Node.js and npm respectively?

Nikos

**Comment by ghost** [comment]
> > npm install serialport@1.6.1
> > does this give you errors

**Comment by nikoagge** [comment]
I can’t do anything because of the same error. :/ Maybe if I update node and npm versions?

Nikos

**Comment by ghost** [comment]
One last thought. Are you using a fork/clone of this repo? 
If so can you just do 
sudo rm -f node_modules
sudo npm install serialport@1.6.1

 if this does not succeed then you should investigate those issues.in https://www.npmjs.com/package/serialport

**Comment by nikoagge** [comment]
I ‘ll try what you suggest. I have one last question, do you insist that I should work with node.js 0.11.16 version or can I work with a newer version?

Nikos

**Comment by ghost** [comment]
you should stick at js 0.11.16.

**Comment by nikoagge** [comment]
Ok, I 've reinstalled my OS X and now I 'm gonna try install node.js 0.11.16 with Homebrew

Nikos

**Comment by masterhou** [comment]
node in this path:  /spark-print-mgr/bin/macos/node, it worked well.

**Comment by nikoagge** [comment]
Yes but after two months I ‘ve still couldn’t installed it properly and I can’t understand which is the problem. The problem is with npm install and missing dependencies, maybe could you help me?

**Comment by nikoagge** [comment]
Well for the two past months I have been trying this tutorial from Spark https://spark.autodesk.com/developers/reference/printer-manufacturers/integrate-your-printer/integrate-your-printer-model https://spark.autodesk.com/developers/reference/printer-manufacturers/integrate-your-printer/integrate-your-printer-model and as step 1 redirected me here but I ‘ve tried everything and still not able to install print manager properly. I can’t understand what I do wrong or if the repository has some errors which need to be solved. Well the problems start when I type npm install on terminal, I ‘ve also clean installed my OSX Yosemite but the problems still are here. I attach the terminal output when i type npm install and I hope that you could help me, thank you in advance. 

Nikos

> On 31 May 2016, at 17:17, Νίκος Αγγελίδης nikoagge@gmail.com wrote:
> 
> Yes but after two months I ‘ve still couldn’t installed it properly and I can’t understand which is the problem. The problem is with npm install and missing dependencies, maybe could you help me?
> 
> > On 31 May 2016, at 06:29, Thomas <notifications@github.com <mailto:notifications@github.com>> wrote:
> > 
> > node in this path: /spark-print-mgr/bin/macos/node, it work well.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub https://github.com/spark3dp/print-manager/issues/28#issuecomment-222584908, or mute the thread https://github.com/notifications/unsubscribe/ALtYFkb23EuYhL1T53NLnG_Ag9h-IuBSks5qG6sUgaJpZM4IXy5m.

Last login: Mon May 30 18:43:49 on ttys000
nikoss-mbp:~ Nikos$ cd /Users/Nikos/Desktop/Spark/print-manager-1.5.1/spark-print-mgr
nikoss-mbp:spark-print-mgr Nikos$ npm install
npm WARN package.json sparkprint@0.0.0 No repository field.

> usb-detection@1.0.3 preinstall /Users/Nikos/Desktop/Spark/print-manager-1.5.1/spark-print-mgr/node_modules/usb-detection
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/detection/src/detection.o
In file included from ../src/detection.cpp:1:
../src/detection.h:15:34: error: no type named 'Arguments' in namespace 'v8';
      did you mean 'v8::internal::Arguments'?
v8::Handlev8::Value Find(const v8::Arguments& args);
                                 ^~~~~~~~~~~~~
                                 v8::internal::Arguments
/Users/Nikos/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/detection.cpp:1:
../src/detection.h:16:15: error: unknown type name 'uv_work_t'
void EIO_Find(uv_work_t\* req);
              ^
../src/detection.h:17:20: error: unknown type name 'uv_work_t'
void EIO_AfterFind(uv_work_t\* req);
                   ^
../src/detection.h:19:45: error: no type named 'Arguments' in namespace 'v8';
      did you mean 'v8::internal::Arguments'?
v8::Handlev8::Value StartMonitoring(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/Nikos/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/detection.cpp:1:
../src/detection.h:21:44: error: no type named 'Arguments' in namespace 'v8';
      did you mean 'v8::internal::Arguments'?
v8::Handlev8::Value StopMonitoring(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/Nikos/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/detection.cpp:1:
../src/detection.h:35:43: error: no type named 'Arguments' in namespace 'v8';
      did you mean 'v8::internal::Arguments'?
v8::Handlev8::Value RegisterAdded(const v8::Arguments& args);
                                          ^~~~~~~~~~~~~
                                          v8::internal::Arguments
/Users/Nikos/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/detection.cpp:1:
../src/detection.h:37:45: error: no type named 'Arguments' in namespace 'v8';
      did you mean 'v8::internal::Arguments'?
v8::Handlev8::Value RegisterRemoved(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/Nikos/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/detection.cpp:19:43: error: no type named 'Arguments' in namespace 'v8';
      did you mean 'v8::internal::Arguments'?
v8::Handlev8::Value RegisterAdded(const v8::Arguments& args)
                                          ^~~~~~~~~~~~~
                                          v8::internal::Arguments
/Users/Nikos/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/detection.cpp:21:19: error: calling a protected constructor of class
      'v8::HandleScope'
  v8::HandleScope scope;
                  ^
/Users/Nikos/.node-gyp/0.11.16/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../src/detection.cpp:25:11: error: member access into incomplete type 'const
      v8::internal::Arguments'
  if (args.Length() == 0)
          ^
/Users/Nikos/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: forward
      declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/detection.cpp:27:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(v8::ThrowException(v8::Exception::TypeError(v8::S...
           ~~~~~ ^
../src/detection.cpp:27:28: error: no member named 'ThrowException' in namespace
      'v8'
    return scope.Close(v8::ThrowException(v8::Exception::TypeError(v8::S...
                       ~~~~^
../src/detection.cpp:27:80: error: no member named 'New' in 'v8::String'
  ...scope.Close(v8::ThrowException(v8::Exception::TypeError(v8::String::New(...
                                                             ~~~~~~~~~~~~^
../src/detection.cpp:30:11: error: member access into incomplete type 'const
      v8::internal::Arguments'
  if (args.Length() == 1)
          ^
/Users/Nikos/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: forward
      declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/detection.cpp:33:13: error: type 'const v8::internal::Arguments' does not
      provide a subscript operator
    if(!args[0]->IsFunction())
        ~~~~^~
../src/detection.cpp:35:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(v8::ThrowException(v8::Exception::TypeError(v...
               ~~~~~ ^
../src/detection.cpp:35:32: error: no member named 'ThrowException' in namespace
      'v8'
        return scope.Close(v8::ThrowException(v8::Exception::TypeError(v...
                           ~~~~^
../src/detection.cpp:35:84: error: no member named 'New' in 'v8::String'
  ...scope.Close(v8::ThrowException(v8::Exception::TypeError(v8::String::New(...
                                                             ~~~~~~~~~~~~^
../src/detection.cpp:38:20: error: type 'const v8::internal::Arguments' does not
      provide a subscript operator
    callback = args[0];
               ~~~~^~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: **\* [Release/obj.target/detection/src/detection.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Nikos/Desktop/Spark/print-manager-1.5.1/spark-print-mgr/node_modules/usb-detection
gyp ERR! node -v v0.11.16
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN optional dep failed, continuing usb-shyp-win32-x64@1.0.5
npm WARN optional dep failed, continuing usb-shyp-win32-ia32@1.0.5

> mdns@2.2.4 install /Users/Nikos/Desktop/Spark/print-manager-1.5.1/spark-print-mgr/node_modules/mdns
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/dns_sd_bindings.node
  SOLINK_MODULE(target) Release/dns_sd_bindings.node: Finished

> serialport@1.6.1 install /Users/Nikos/Desktop/Spark/print-manager-1.5.1/spark-print-mgr/node_modules/serialport
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
../src/serialport_unix.cpp:663:20: warning: comparison of array
      'device.locationId' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
        if (device.locationId != NULL) {
            ~~~~~~~^~~~~~~~~~    ~~~~
../src/serialport_unix.cpp:666:20: warning: comparison of array
      'device.vendorId' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
        if (device.vendorId != NULL) {
            ~~~~~~~^~~~~~~~    ~~~~
../src/serialport_unix.cpp:669:20: warning: comparison of array
      'device.productId' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
        if (device.productId != NULL) {
            ~~~~~~~^~~~~~~~~    ~~~~
../src/serialport_unix.cpp:672:20: warning: comparison of array
      'device.manufacturer' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
        if (device.manufacturer != NULL) {
            ~~~~~~~^~~~~~~~~~~~    ~~~~
../src/serialport_unix.cpp:675:20: warning: comparison of array
      'device.serialNumber' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
        if (device.serialNumber != NULL) {
            ~~~~~~~^~~~~~~~~~~~    ~~~~
5 warnings generated.
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/serialport.node
  SOLINK_MODULE(target) Release/serialport.node: Finished
  COPY /Users/Nikos/Desktop/Spark/print-manager-1.5.1/spark-print-mgr/node_modules/serialport/build/serialport/v1.6.1/Release/node-v14-darwin-x64/serialport.node
  TOUCH Release/obj.target/action_after_build.stamp

> usb@1.0.5 install /Users/Nikos/Desktop/Spark/print-manager-1.5.1/spark-print-mgr/node_modules/usb
> node shyp-blacklist.js win32-x64 win32-ia32 darwin-x64 || node-gyp rebuild

npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.11.16
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! usb-detection@1.0.3 preinstall: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb-detection@1.0.3 preinstall script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the usb-detection package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls usb-detection
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Nikos/Desktop/Spark/print-manager-1.5.1/spark-print-mgr/npm-debug.log
nikoss-mbp:spark-print-mgr Nikos$

**Comment by jmkao** [comment]
You are having difficulties installing gyp, which was the most difficult problem I had to overcome when setting up a dev environment on Windows.

Fortunately, in the node community, there is a large amount of documentation on how to get this installed. You should search the Internet for documentation on installing gyp for your OS version, in particular there are a large number of requirements around having specific versions of the C/C++ development toolchain that match your OS version.

**Comment by nikoagge** [comment]
So to understand it better, this is the problem? I want to know if I ‘m doing any other mistake? I mean I download from here https://github.com/spark3dp/print-manager/releases https://github.com/spark3dp/print-manager/releases and from Open Source Print Manager 1.5.1 the source code and RoopaServer-0d221eaMacOS.tar.gz https://github.com/spark3dp/print-manager/releases/download/1.5.1/RoopaServer-0d221eaMacOS.tar.gz, or should I download previous releases and which?

Nikos

**Comment by ghost** [comment]
You can narrow the scope of the problem by just trying to install 1 npm package that requires gyp.

eg
cd ~/Documents
mkdir testgyp
cd testgyp
npm install usb-detection@1.3.0

Then as @jmkao suggests  search the Internet for documentation on installing gyp for your OS version and c++ compiler set up

**Comment by nikoagge** [comment]
You mean documents folder or on spark-print-manager file?

Nikos

**Comment by ghost** [comment]
What I am trying to point out is that this is any folder you want. This has nothing to do with print manager. So in short I mean documents folder.

**Comment by nikoagge** [comment]
Ok I ‘ll try it know and gonna let you about the result

Nikos
